
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 65)
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 42;
  public static final int POW = 31;
  public static final int PARENTESISCIERRE = 9;
  public static final int POR = 27;
  public static final int CHAR = 14;
  public static final int CHARELEMENT = 46;
  public static final int CASE = 40;
  public static final int INT = 15;
  public static final int PUNTOCOMA = 10;
  public static final int DEFINE = 3;
  public static final int NOT = 32;
  public static final int AND = 30;
  public static final int IGUAL = 35;
  public static final int LT = 22;
  public static final int OR = 26;
  public static final int BOOL = 13;
  public static final int GET = 21;
  public static final int DIV = 28;
  public static final int IDFP = 44;
  public static final int IF = 36;
  public static final int ID = 43;
  public static final int EOF = 0;
  public static final int LLAVECIERRE = 7;
  public static final int LLAVEAPERTURA = 6;
  public static final int RETURN = 17;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int REALELEMENT = 48;
  public static final int MENOS = 25;
  public static final int MOD = 29;
  public static final int NEQ = 19;
  public static final int START = 4;
  public static final int BOOLELEMENT = 45;
  public static final int EQ = 18;
  public static final int PARENTESISAPERTURA = 8;
  public static final int DECLARE = 2;
  public static final int SWITCH = 39;
  public static final int REAL = 16;
  public static final int ELSE = 37;
  public static final int CORCHETECIERRE = 34;
  public static final int INTELEMENT = 47;
  public static final int WHILE = 38;
  public static final int DEFAULT = 41;
  public static final int LET = 20;
  public static final int END = 5;
  public static final int PROC = 12;
  public static final int CORCHETEAPERTURA = 33;
  public static final int GT = 23;
  public static final int MAS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECLARE",
  "DEFINE",
  "START",
  "END",
  "LLAVEAPERTURA",
  "LLAVECIERRE",
  "PARENTESISAPERTURA",
  "PARENTESISCIERRE",
  "PUNTOCOMA",
  "COMA",
  "PROC",
  "BOOL",
  "CHAR",
  "INT",
  "REAL",
  "RETURN",
  "EQ",
  "NEQ",
  "LET",
  "GET",
  "LT",
  "GT",
  "MAS",
  "MENOS",
  "OR",
  "POR",
  "DIV",
  "MOD",
  "AND",
  "POW",
  "NOT",
  "CORCHETEAPERTURA",
  "CORCHETECIERRE",
  "IGUAL",
  "IF",
  "ELSE",
  "WHILE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "DOSPUNTOS",
  "ID",
  "IDFP",
  "BOOLELEMENT",
  "CHARELEMENT",
  "INTELEMENT",
  "REALELEMENT"
  };
}

